# Generated by Django 4.1.6 on 2023-06-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_is_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otchestvo',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pin',
            field=models.CharField(blank=True, default='', max_length=14, null=True),
        ),
    ]
