# Generated by Django 4.1.6 on 2023-06-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_area_city_alter_city_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='ticket.area'),
        ),
    ]
