# Generated by Django 4.1.6 on 2023-06-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_offlineticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlineticket',
            name='activation_code',
        ),
    ]
