# Generated by Django 4.1.6 on 2023-06-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_remove_offlineticket_activation_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfflineTicket',
        ),
    ]
