# Generated by Django 4.1.6 on 2023-06-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_offileticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offileticket',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
