# Generated by Django 4.1.6 on 2023-06-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_alter_offileticket_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offileticket',
            old_name='status',
            new_name='status1',
        ),
    ]
