# Generated by Django 4.1.6 on 2023-06-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_rename_status_offileticket_status1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offileticket',
            name='status1',
            field=models.BooleanField(default=False),
        ),
    ]
