# Generated by Django 4.1.6 on 2023-06-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_alter_offileticket_status1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offileticket',
            old_name='status1',
            new_name='status',
        ),
    ]
