# Generated by Django 4.1.6 on 2023-06-29 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ticket', '0015_rename_status1_offileticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offileticket',
            name='queue_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offileticket',
            name='queue_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='queue_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='queue_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.region', verbose_name='Область'),
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.PositiveIntegerField()),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
