# Generated by Django 4.1.6 on 2023-06-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='offileticket',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.category'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.category'),
        ),
    ]
