# Generated by Django 4.1.6 on 2023-06-30 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0019_offileticket_category_ticket_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6)),
                ('is_served', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offline_ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.offileticket')),
                ('online_ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('online_ticket', 'offline_ticket', 'number')},
            },
        ),
    ]
